# Copyright WalmartLabs. All Rights Reserved.
# author: anand.banik@walmartlabs.com
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  orderer.walmartlabs.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.walmartlabs.com
    container_name: orderer.walmartlabs.com
    networks:
      - byfn

  peer0.dealer.walmartlabs.com:
    container_name: peer0.dealer.walmartlabs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dealer.walmartlabs.com
    networks:
      - byfn

  peer0.insurance.walmartlabs.com:
    container_name: peer0.insurance.walmartlabs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.walmartlabs.com
    networks:
      - byfn

  peer0.banker.walmartlabs.com:
    container_name: peer0.banker.walmartlabs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.banker.walmartlabs.com
    networks:
      - byfn
  
  peer0.dmv.walmartlabs.com:
    container_name: peer0.dmv.walmartlabs.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.dmv.walmartlabs.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.dealer.walmartlabs.com:7051
      - CORE_PEER_LOCALMSPID=DealerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dealer.walmartlabs.com/peers/peer0.dealer.walmartlabs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dealer.walmartlabs.com/peers/peer0.dealer.walmartlabs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dealer.walmartlabs.com/peers/peer0.dealer.walmartlabs.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dealer.walmartlabs.com/users/Admin@dealer.walmartlabs.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/walmartlabs/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.walmartlabs.com
      - peer0.dealer.walmartlabs.com
      - peer0.insurance.walmartlabs.com
      - peer0.banker.walmartlabs.com
    networks:
      - byfn

