# Copyright WalmarLabs. All Rights Reserved.
# author: anand.banik@walmartlabs.com
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.walmartlabs.com:
    container_name: orderer.walmartlabs.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/walmartlabs.com/orderers/orderer.walmartlabs.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/walmartlabs.com/orderers/orderer.walmartlabs.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.dealer.walmartlabs.com:
    container_name: peer0.dealer.walmartlabs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dealer.walmartlabs.com
      - CORE_PEER_ADDRESS=peer0.dealer.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dealer.walmartlabs.com:7051
      - CORE_PEER_LOCALMSPID=DealerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dealer.walmartlabs.com/peers/peer0.dealer.walmartlabs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dealer.walmartlabs.com/peers/peer0.dealer.walmartlabs.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.insurance.walmartlabs.com:
    container_name: peer0.insurance.walmartlabs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.walmartlabs.com
      - CORE_PEER_ADDRESS=peer0.insurance.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.walmartlabs.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.walmartlabs.com/peers/peer0.insurance.walmartlabs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.walmartlabs.com/peers/peer0.insurance.walmartlabs.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.banker.walmartlabs.com:
    container_name: peer0.banker.walmartlabs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.banker.walmartlabs.com
      - CORE_PEER_ADDRESS=peer0.banker.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.banker.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.banker.walmartlabs.com:7051
      - CORE_PEER_LOCALMSPID=BankerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/banker.walmartlabs.com/peers/peer0.banker.walmartlabs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/banker.walmartlabs.com/peers/peer0.banker.walmartlabs.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer0.dmv.walmartlabs.com:
    container_name: peer0.dmv.walmartlabs.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dmv.walmartlabs.com
      - CORE_PEER_ADDRESS=peer0.dmv.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dmv.walmartlabs.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dmv.walmartlabs.com:7051
      - CORE_PEER_LOCALMSPID=DmvMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dmv.walmartlabs.com/peers/peer0.dmv.walmartlabs.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dmv.walmartlabs.com/peers/peer0.dmv.walmartlabs.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
